-- Registered plugin functions from Compas v1.0.1 (Plugin API 15).
-- Freeze this surface so mocks cannot quietly invent newer APIs.
local allowed = {
    ["api_version"] = true,
    ["cancel"] = true,
    ["clear_interval"] = true,
    ["define"] = true,
    ["delete"] = true,
    ["download_file_async"] = true,
    ["eq_load_profile"] = true,
    ["eq_reset"] = true,
    ["eq_save_profile"] = true,
    ["eq_set_band"] = true,
    ["eq_set_band_enabled"] = true,
    ["eq_set_band_type"] = true,
    ["eq_set_bypass"] = true,
    ["eq_set_preamp"] = true,
    ["exists"] = true,
    ["get"] = true,
    ["get_album_tracks"] = true,
    ["get_app_info"] = true,
    ["get_artist_albums"] = true,
    ["get_battery"] = true,
    ["get_current_track_path"] = true,
    ["get_duration"] = true,
    ["get_next_album_tracks"] = true,
    ["get_now_playing"] = true,
    ["get_play_mode"] = true,
    ["get_position"] = true,
    ["get_volume"] = true,
    ["has_capability"] = true,
    ["html_to_blocks"] = true,
    ["http_get"] = true,
    ["http_post"] = true,
    ["http_request"] = true,
    ["image_thumbnail_async"] = true,
    ["is_list_showing"] = true,
    ["is_paused"] = true,
    ["is_playing"] = true,
    ["json_decode"] = true,
    ["json_encode"] = true,
    ["led_available"] = true,
    ["led_blink"] = true,
    ["led_breathe"] = true,
    ["led_get"] = true,
    ["led_release"] = true,
    ["led_set"] = true,
    ["led_status"] = true,
    ["library_get_albums"] = true,
    ["library_get_artists"] = true,
    ["library_get_song"] = true,
    ["library_get_songs"] = true,
    ["library_search"] = true,
    ["library_song_count"] = true,
    ["list"] = true,
    ["list_dir"] = true,
    ["md5"] = true,
    ["media_capabilities"] = true,
    ["mkdir"] = true,
    ["next_track"] = true,
    ["on"] = true,
    ["play_file"] = true,
    ["play_list"] = true,
    ["play_remote"] = true,
    ["playlist_add"] = true,
    ["playlist_create"] = true,
    ["playlist_delete"] = true,
    ["playlist_list"] = true,
    ["playlist_read"] = true,
    ["playlist_remove"] = true,
    ["prev_track"] = true,
    ["queue_remote_list"] = true,
    ["refresh_library"] = true,
    ["refresh_theme"] = true,
    ["register_home_tile"] = true,
    ["register_list_item"] = true,
    ["register_quick_toggle"] = true,
    ["register_stream_media_tile"] = true,
    ["reload_ui"] = true,
    ["screenshot"] = true,
    ["sd_root"] = true,
    ["secrets"] = true,
    ["storage"] = true,
    ["seek"] = true,
    ["set"] = true,
    ["set_background_color"] = true,
    ["set_home_layout"] = true,
    ["set_hw_volume_curve"] = true,
    ["set_icon"] = true,
    ["set_interval"] = true,
    ["set_launcher_layout"] = true,
    ["set_player_layout"] = true,
    ["set_quick_toggle"] = true,
    ["set_text_color"] = true,
    ["set_transport_skip"] = true,
    ["set_volume"] = true,
    ["show_list"] = true,
    ["show_lock_screen"] = true,
    ["show_settings_list"] = true,
    ["show_text_input"] = true,
    ["show_text_view"] = true,
    ["show_toast"] = true,
    ["stop"] = true,
    ["toggle_pause"] = true,
    ["zip_image_async"] = true,
    ["zip_list"] = true,
    ["zip_read"] = true,
}
return function(plugin)
    for name in pairs(plugin) do
        assert(allowed[name], "Mock defines a function absent from API 15: " .. name)
    end
    return setmetatable(plugin, {
        __index = function(_, name)
            error("Plugin accessed an unmocked or unsupported API 15 field: " .. tostring(name), 2)
        end,
    })
end
